"""Body file format — TSK mactime-compatible output."""

# Body file format documentation:
# MD5|name|inode|mode_as_string|UID|GID|size|atime|mtime|ctime|crtime
# Each field is separated by |
# Timestamps are Unix epoch (seconds since 1970-01-01)

BODY_FILE_HEADER = "# Body file generated by DEADDROP Digital Forensics Toolkit\n"